[package]
name = "canarywatcher"
version = "0.1.0"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
description = "Lock your system when canary directory is touched"
license = "GPLv3"

[dependencies]
inotify = "0.4"
