[package]
name = "canarywatcher"
version = "0.1.2"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
description = "Lock your system when canary directory is touched"
license = "GPL-3.0"

[dependencies]
inotify = "0.5.1"
